create table if not exists shop_detail
(
	shop_id bigint null,
	shop_classify int null,
	shop_trademark_type int null,
	shop_trademark_attribute int null,
	shop_area int null,
	shop_category int null,
	shop_fulfill_target int null,
	shop_loan_quota decimal(10,2) null,
	shop_loaned decimal(10,2) null,
	shop_turnover decimal(10,2) null,
	shop_bring_goods int null,
	shop_provide_channels int null,
	shop_fans int null,
	shop_level int null,
	shop_reputation int null,
	shop_online_time timestamp null,
	shop_collection int null,
	shop_fits_description decimal(4,2) null,
	shop_fits_description_rate int null,
	shop_fits_description_number int null,
	shop_seller_service decimal(4,2) null,
	shop_seller_service_rate int null,
	shop_seller_service_number int null,
	shop_delivery_speed decimal(4,2) null,
	shop_delivery_speed_rate int null,
	shop_delivery_speed_number int null,
	shop_main_products varchar(512) null,
	shop_second_hand int null,
	company_name tinytext null,
	registered_capital decimal(11,1) null,
	taxpayer_type int null,
	exclusive int null,
	company_detail tinytext null,
	wechat tinytext null,
	user_phone bigint null,
	user_name tinytext null,
	area tinytext null
)
comment '网店详情表,shop附属表一对一,参数修改一定要关联shop表';

